//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpeakOutWeb.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SpeakOutEntities : DbContext
    {
        public SpeakOutEntities()
            : base("name=SpeakOutEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<UserAcceptance> UserAcceptances { get; set; }
        public virtual DbSet<UserGroupDetail> UserGroupDetails { get; set; }
        public virtual DbSet<UserGroup> UserGroups { get; set; }
        public virtual DbSet<Vocabulary> Vocabularies { get; set; }
        public virtual DbSet<UserAudio> UserAudioes { get; set; }
        public virtual DbSet<UserAudioGroup> UserAudioGroups { get; set; }
        public virtual DbSet<UserLog> UserLogs { get; set; }
    }
}
