//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpeakOutWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAudioGroup
    {
        public int Id { get; set; }
        public Nullable<int> IdGroups { get; set; }
        public Nullable<int> IdAudio { get; set; }
    
        public virtual UserAudio UserAudio { get; set; }
    }
}
