//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpeakOutWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserGroupDetail
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string StudentName { get; set; }
        public string StudentEmail { get; set; }
        public Nullable<int> GroupId { get; set; }
    
        public virtual UserGroup UserGroup { get; set; }
    }
}
