//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpeakOutWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vocabulary
    {
        public int Id { get; set; }
        public string EngWord { get; set; }
        public string VnWord { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string Spelling { get; set; }
        public string UserId { get; set; }
        public Nullable<bool> Bookmark { get; set; }
    }
}
